# Generated by Django 4.2.6 on 2023-10-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
