# Generated by Django 4.2.6 on 2023-10-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
