# Generated by Django 4.2.6 on 2023-10-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
